name: Build and Deploy to Local IIS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted  # 使用本機 GitHub Runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

   # - name: Run tests
   #   run: dotnet test --no-build --verbosity normal

    - name: Publish project
      run: dotnet publish ./personal_tasks.csproj -c Release -o ./publish

    - name: Deploy to IIS
      shell: powershell
      run: |
        $sitePath = "C:\inetpub\wwwroot\YourSite"
        if (Test-Path $sitePath) {
          Remove-Item -Recurse -Force "$sitePath\*"
        } else {
          New-Item -ItemType Directory -Path $sitePath
        }
        Copy-Item -Path "./publish/*" -Destination $sitePath -Recurse
        Restart-WebAppPool -Name "YourAppPoolName"
        Write-Host "✅ Deployment to IIS completed."
