name: Build and Deploy to Local IIS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted  # 使用本機 GitHub Runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --no-build --configuration Release --verbosity normal ./TestProject1/TestProject1.csproj

    - name: Publish project
      run: dotnet publish ./personal_tasks/personal_tasks.csproj -c Release -o ./publish

    - name: Deploy to IIS
      shell: powershell
      run: |
       $baseDeployPath = "G:\code\Csharp\CI_test"
        $appPool = "CI_test"
        $timestamp = Get-Date -Format "yyyyMMddHHmmss"
        $newDeployFolder = Join-Path $baseDeployPath "release-$timestamp"

        # 建立新資料夾
        New-Item -Path $newDeployFolder -ItemType Directory -Force | Out-Null

        # 複製publish下所有內容
        Copy-Item -Path "./publish\*" -Destination $newDeployFolder -Recurse -Force

        # Update IIS site physical path to the new folder
        Import-Module WebAdministration
        Set-ItemProperty "IIS:\Sites\$appPool" -Name physicalPath -Value $newDeployFolder

        # Restart App Pool
        try {
          Restart-WebAppPool -Name $appPool
          Write-Host "✅ App pool '$appPool' restarted."
        } catch {
          Write-Warning "⚠️ App pool '$appPool' restart failed: $_"
        }

        # Clean up old deployments, keep only the latest 3
        $folders = Get-ChildItem -Path $baseDeployPath -Directory | Where-Object { $_.Name -like "release-*" } | Sort-Object Name -Descending
        $foldersToRemove = $folders | Select-Object -Skip 3
        foreach ($folder in $foldersToRemove) {
          try {
            Remove-Item -Path $folder.FullName -Recurse -Force
            Write-Host "🗑️ Removed old deployment folder: $($folder.FullName)"
          } catch {
            Write-Warning "⚠️ Failed to remove folder: $($folder.FullName) - $_"
          }
        }

        Write-Host "✅ Deployment to IIS site '$appPool' with versioned folder completed."

