name: Build and Deploy to Local IIS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted  # 使用本機 GitHub Runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

   # - name: Run tests
   #   run: dotnet test --no-build --verbosity normal

    - name: Publish project
      run: dotnet publish ./personal_tasks/personal_tasks.csproj -c Release -o ./publish

    - name: Deploy to IIS
      shell: powershell
      run: |
       $sitePath = "G:\code\Csharp\CI_test"
        $appPool = "CI_test"
        Stop-WebAppPool -Name $appPool
        Start-Sleep -Seconds 5 
        Get-ChildItem -Path $sitePath -Recurse -Force -ErrorAction SilentlyContinue | ForEach-Object {
          try {
            $_.IsReadOnly = $false
          } catch {}
        }
        Get-ChildItem -Path $sitePath -Recurse -Force -ErrorAction SilentlyContinue | ForEach-Object {
          try {
            Remove-Item -Path $_.FullName -Force -Recurse -ErrorAction Stop
          } catch {
            Write-Warning "⚠️ 無法刪除檔案：$($_.FullName) - $_"
          }
        }
        Copy-Item -Path "./publish/*" -Destination $sitePath -Recurse -Force
        Start-WebAppPool -Name $appPool
        Write-Host "✅ Deployment to IIS site '$appPool' completed."

